import dynamic from "next/dynamic";
import Head from "next/head";

// @ts-ignore
const Engine = dynamic(() => import("engine/components/Engine"));

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Engine
          // @ts-ignore
          onSubmit={(e) => {
            e.preventDefault();

            console.log("submit");
          }}
        />
      </main>
    </>
  );
}
